export async function signup(params) {
  const email = params.email;

  const publicKey = {
    challenge: new Uint8Array(32), // A random value generated by the server
    rp: {
      name: "YourAppName",
    },
    user: {
      id: new Uint8Array(16), // Unique user ID
      name: email,
      displayName: "User Name",
    },
    pubKeyCredParams: [{ alg: -7, type: "public-key" }],
    authenticatorSelection: {
      authenticatorAttachment: "platform", // To use built-in biometric sensor
      userVerification: "required",
    },
    timeout: 60000,
    attestation: "direct",
  };

  try {
    const credential = await navigator.credentials.create({
      publicKey,
    });
    console.log("Registration successful", credential);
    // Send `credential` to the server for verification and storage
  } catch (err) {
    console.error("Registration failed", err);
  }

  // const data = await navigator.credentials.create({
  //     publicKey: {
  //         challenge: new Uint8Array(32),
  //         rp: { name: "auth app lick a ti on" },
  //         user: {
  //             id: new Uint8Array(16),
  //             name: email,
  //             displayName : ""
  //         },
  //         pubKeyCredParams: [
  //             { type: "public-key", alg: -7 },
  //             {type : "public-key", alg : -8},
  //             {type : "public-key", alg : -257},
  //         ]
  //     }
  // })

  //  startRegistration();

  console.log(data);
}

export function login() {}
